### ISSUE TITLE
Components not displayed properly in IE11

### ISSUE THREAD

**Issue by aigtest** [vaadin/board#130] opened 2017-12-06 12:19 UTC
I am using the default bakery demo project
vaadin board 1.1.0-beta1 or  1.0.1 or 1.0
vaadin 8.1.6 or 8.2.0beta
IE version 11.0.9600.18816
1920x1080 windows screen

The same demo runs perfectly in chrome or firefox. 
I have contact vaadin sales ppl, they asked me register an issue here.

**Comment by vlukashov** [comment] 2017-12-07 06:03
Thanks for reporting the issue here, @aigtest! Could you please attach a screenshot of the broken page in IE11?

**Comment by aigtest** [comment] 2017-12-11 01:21
![ie version](https://user-images.githubusercontent.com/34306122/33812035-fc685ce2-de5c-11e7-94e4-76ab5a05a408.png)
![vaadin board](https://user-images.githubusercontent.com/34306122/33812036-fcc17610-de5c-11e7-8b90-e4ed5873a17f.jpg)

I have uploaded the screenshot, please confirm.

**Comment by vlukashov** [comment] 2017-12-11 05:05
Thanks for the screenshot and the IE version information!
When did you download the starter source code from vaadin.com? This (or a very similar) issue was recently fixed and the fix is included into all fresh Bakery app starter source packages.

Could you possibly check whether or not the issue is there if you download a fresh copy of the Bakery app starter source from https://vaadin.com/start?

**Comment by johannesh2** [comment] 2018-05-14 13:51
I am closing this ticket, which is accidentally left open as cannot reproduce. I tested it now with IE 11.431.16299.0. Please re-open if this is still an issue.

**Closed by johannesh2** 2018-05-14 13:51 UTC
